### PR TITLE
Update to Orleans 1.5.0

### PR DESCRIPTION
**Pull request by ibebbs**
Hi,

I've updated Orleans references to the latest version (1.5.0) and fixed up all breaking changes.

Lots of the unit tests pass when run against a local Kafka instance but some require additional configuration that I've not had time to try and some have issues due to using a deprecated test framework ('TestingSiloHost' is obsolete: 'Use TestCluster').

I've test it as a stream provider in a TestCluster and, while I can see that messages are definitely being published to and received from Kafka, for some reason the received messages aren't hitting my grain (I'm just waiting for symbols for Orleans to become available so I can continue digging).

Anyway, I'd very much like to know what you think of the changes. Seems a shame that this repo hasn't been updated in a while. Would be good to move to a more recent Kafka API version.

Cheers,
  Ian

### CODE REVIEW

**Comment by tsibelman** [comment]
First of all great work thank you very much for your contribution it definitely something that was on our todo list . I will run it against our internal Kafka servers and see if I can help you with debugging the issue. We also internally talking about using new official .NET kafka client that uses new consumers so if it something you like to start investigating  we will be happy to assist you.

**Comment by ibebbs** [comment]
No problem. It was a nice code-base to work on. 

Which .NET Kafka client were you intending to use? [This one](https://www.nuget.org/packages/Confluent.Kafka/0.11.0-RC1)?

**Comment by tsibelman** [comment]
Yes this is the client i was referring to.

**Comment by EranOfer** [comment]
I did some digging and I found how you can fix all the test except one.
Please have a look at the branch 'feature/fixTest' .
You can view the change in this [commit](https://github.com/gigya/Orleans.KafkaStreamProvider/commit/73516cf74223e67830b92dcb7c23a1ebfe143bd9).

**Comment by EranOfer** [comment]
Hi @ibebbs ,
I've opened a new merge [request](https://github.com/ibebbs/Orleans.KafkaStreamProvider/pull/1)  for you please review the change .
Thanks,
Eran

**Comment by ibebbs** [comment]
Thanks Eran. I've merged the changeset and will hopefully have time to test the changes later.

FYI, I'm not sure you realised from my other PR #22 but the KafkaStreamProvider has been working fine in Orleans 1.5.0 and I've been using it to send and receive messages to/from grains.

Great to have the (very extensive!) test suite passing again though.

**Pull request merged**
